### ISSUE TITLE
Recent yarl update breaks homeassistant

### ISSUE THREAD

**Issue by tiagoboldt** [kamaradclimber/home-assistant-aur#4]
So, a recent yarl update (v >= 1.0.0) breaks homeassistant since it removed the quote and unquote functions. 

My suggestion is to use a virtualenv to lock homeassistant's dependencies instead of using the ones available in the system, preventing this from happening in the future.

**Comment by kamaradclimber** [comment]
Thanks for the suggestion.
Since I provide a package for archlinux I believe I should try to use system packages as much as possible. Other options to run home-assistant (such as any container image) would allow to get rid of coupling with the system.

I'll try to sort out the yarl issue when pushing 0.62 package.
